version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: iqair
      MYSQL_ROOT_PASSWORD: iqair
    networks:
      - iqair_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=iqair
      - DB_DATABASE=iqair
    ports:
      - '3000:3000'
    networks:
      - iqair_network

networks:
  iqair_network:
    driver: bridge